# Generated by Django 4.2.8 on 2023-12-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="item", options={"ordering": ["-created"]},),
        migrations.RenameField(model_name="item", old_name="name", new_name="title",),
        migrations.AddField(
            model_name="item", name="description", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
