# Generated by Django 4.2.8 on 2023-12-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_item_options_rename_name_item_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
